### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by kaedys** [viktor-ferenczi/performance-improvements#41]
The commit referenced in the current plugin hub, [427df30](https://github.com/sepluginloader/PluginHub/blob/main/Plugins/PerformanceImprovements.xml#L7C11-L7C51), appears to no longer exist (did it get force-pushed over?), so loading the plugin via the plugin loader appears to just be hard failing at the download step.  I assume this'll probably be fixed when your latest commit, which was merged ~12 hours ago, gets PR'd into the hub, but I figured I'd give you a head's up anyway.

```
2023-07-30 12:45:41.082 - Thread:   1 ->  [PluginLoader] Starting - v1.11.5
2023-07-30 12:45:43.394 - Thread:   1 ->  [PluginLoader] Downloading https://raw.githubusercontent.com/sepluginloader/PluginHub/main/plugins.sha1
2023-07-30 12:45:43.543 - Thread:   1 ->  [PluginLoader] Downloading https://github.com/sepluginloader/PluginHub/archive/main.zip
2023-07-30 12:45:43.853 - Thread:   1 ->  [PluginLoader] Saving whitelist to disk
2023-07-30 12:45:43.860 - Thread:   1 ->  [PluginLoader] Saving config
2023-07-30 12:45:43.886 - Thread:   1 ->  [PluginLoader] Whitelist updated
2023-07-30 12:45:43.933 - Thread:   1 ->  [PluginLoader] Found 120 plugins
2023-07-30 12:45:43.937 - Thread:   1 ->  [PluginLoader] Found 49 plugin groups
2023-07-30 12:45:43.943 - Thread:   1 ->  [PluginLoader] Enabled plugins: WesternGamer/AddMissingSearchBoxes, austinvaness/BetterInventorySearch, austinvaness/BlockPicker, viktor-ferenczi/se-bugfixes, austinvaness/DisableAnalytics, WesternGamer/FPSCounter, zznty/FactionUnlimiter, StarCpt/SE-GridFilter, austinvaness/MESInhibitorPlugin, viktor-ferenczi/multigrid-projector, Allen-Wrench/NoForcedCameraZoom, WesternGamer/No-News-Plugin, viktor-ferenczi/performance-improvements, WesternGamer/RemoveIntroVideoPlugin, austinvaness/ScrollRotationPlugin, austinvaness/ToolSwitcherPlugin, viktor-ferenczi/toolbar-manager, austinvaness/UnlimitedScriptLength
2023-07-30 12:45:43.944 - Thread:   1 ->  [PluginLoader] Patching
2023-07-30 12:45:43.945 - Thread:  12 ->  [PluginLoader] Downloading plugin statistics anonymously...
2023-07-30 12:45:44.408 - Thread:   1 ->  [PluginLoader] Instantiating plugins
2023-07-30 12:45:44.439 - Thread:   1 ->  [PluginLoader] Precompiling BetterInventorySearch_0dphx2oh.rs5, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:45:44.466 - Thread:   1 ->  [PluginLoader] Precompiling BlockPicker_jqkxmodf.2xy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:45:44.473 - Thread:   1 ->  [PluginLoader] Downloading https://github.com/viktor-ferenczi/multigrid-projector/archive/56ac8a25723b9d69169c521a3b31348ddeb2a296.zip
2023-07-30 12:45:45.621 - Thread:   1 ->  [PluginLoader] Precompiling multigrid_projector_wxw0mxp5.bal, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:45:45.762 - Thread:   1 ->  [PluginLoader] Precompiling NoForcedCameraZoom_ybg3c515.eva, Version=1.0.0.2, Culture=neutral, PublicKeyToken=null
2023-07-30 12:45:45.794 - Thread:   1 ->  [PluginLoader] Precompiling No_News_Plugin_yqxz22s0.5ps, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:45:45.795 - Thread:   1 ->  [PluginLoader] Downloading https://github.com/viktor-ferenczi/performance-improvements/archive/427df307576cb82c23a6659f8cb688870662c3f9.zip
2023-07-30 12:45:45.862 - Thread:   1 ->  [PluginLoader] Failed to load viktor-ferenczi/performance-improvements|Performance Improvements because of an error: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at avaness.PluginLoader.Network.GitHub.GetStream(Uri uri)
   at avaness.PluginLoader.Network.GitHub.DownloadRepo(String name, String commit)
   at avaness.PluginLoader.Data.GitHubPlugin.CompileFromSource(String commit, Action`1 callback)
   at avaness.PluginLoader.Data.GitHubPlugin.GetAssembly()
   at avaness.PluginLoader.Data.PluginData.TryLoadAssembly(Assembly& a)
2023-07-30 12:46:08.870 - Thread:   1 ->  [PluginLoader] Precompiling RemoveIntroVideoPlugin_f55n4wws.h0t, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:08.893 - Thread:   1 ->  [PluginLoader] Precompiling ScrollRotationPlugin_zvapuosa.ev5, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:08.922 - Thread:   1 ->  [PluginLoader] Precompiling toolbar_manager_dzxllufg.40t, Version=1.3.3.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:08.972 - Thread:   1 ->  [PluginLoader] Precompiling AddMissingSearchBoxes_sird4hp4.2pg, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.003 - Thread:   1 ->  [PluginLoader] Precompiling ToolSwitcherPlugin_rq10zky3.3hv, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.058 - Thread:   1 ->  [PluginLoader] Precompiling UnlimitedScriptLength_rjgq1dhg.x11, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.092 - Thread:   1 ->  [PluginLoader] Precompiling DisableAnalytics_acerpwx1.2pw, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.103 - Thread:   1 ->  [PluginLoader] Precompiling FPSCounter_wb4jtg0b.ri5, Version=1.1.4.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.193 - Thread:   1 ->  [PluginLoader] Precompiling FactionUnlimiter_ttmhhrad.se2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.218 - Thread:   1 ->  [PluginLoader] Precompiling SE_GridFilter_04hhi2a5.lda, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.250 - Thread:   1 ->  [PluginLoader] Precompiling MESInhibitorPlugin_ox050dqi.fcv, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.283 - Thread:   1 ->  [PluginLoader] Precompiling se_bugfixes_b2axu3l2.0sy, Version=1.3.6.0, Culture=neutral, PublicKeyToken=null
2023-07-30 12:46:09.303 - Thread:   1 ->  [PluginLoader] Finished startup. Took 28225ms
```

**Comment by SnakeInventor** [comment]
Same

**Comment by kaedys** [comment]
Fixed, much appreciate the revert.
