### ISSUE TITLE
MyShipConnectorPatchForConveyor causing server hang sometimes

### ISSUE THREAD

**Issue by draconb** [viktor-ferenczi/performance-improvements#62]
https://github.com/viktor-ferenczi/performance-improvements/blob/main/Shared/Patches/Conveyor/MyShipConnectorPatchForConveyor.cs

11:04:33.1893 [ERROR]  Torch: Frozen thread dump Main thread
Common prefix:
   at System.Threading.SpinWait.SpinOnce()
   at Shared.Patches.MyShipConnectorPatchForConveyor.OnConnectionStateChangedPostfix(MyShipConnector __instance)
   at Sandbox.Game.Entities.Cube.MyShipConnector.OnConnectionStateChanged_Patch1(MyShipConnector this)
   at System.Action`1.Invoke(T obj)
   at VRage.Sync.SyncBase.RaiseValueChanged(Boolean notify)
   at VRage.Sync.Sync`2.SetValue(T& newValue, Boolean validate, Boolean ignoreSyncDirection, Boolean received)
   at Sandbox.Game.Entities.Cube.MyShipConnector.Detach(Boolean synchronize)
   at Sandbox.Game.Entities.Cube.MyShipConnector.TryDisconnect()
   at Sandbox.Game.GameSystems.MyGridConveyorSystem.ToggleConnectors(Nullable`1 targetState, Boolean forceToggle)
   at Sandbox.Game.Entities.MyCubeGrid.SetParkedStateInternal(Boolean v)
   at Sandbox.Game.Entities.MyCubeGrid.ToggleParkStateRequest()
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at Patched_VRage.Network.MyReplicationServerOnEvent_0(Object site, MyPacketDataBitStreamBase obj, CallSite sendAs, Object position, IMyNetObject source, Nullable`1 , EndpointId )
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
   at Patched_Sandbox.Engine.Networking.MyNetworkReaderProcess_0()
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 326
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 126
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Suffix 0
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)

Suffix 1
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)

Suffix 2
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)

**Comment by viktor-ferenczi** [comment]
Does the problem disappear if you uncheck the `FixConveyor` (Conveyor network performance fixes) configuration option of the plugin?

**Comment by draconb** [comment]
It's been a random crash for a while I can get more details and try disabling it for now

**Comment by draconb** [comment]
Just an FYI we've had 7 crashes with this as the reason in the last 8 days. A few of them occured shortly after !fixship was run on what appears to be connected grids.

**Comment by viktor-ferenczi** [comment]
Have these crashes occurred with the `FixConveyor` (Conveyor network performance fixes) configuration option ON or OFF?

**Comment by draconb** [comment]
> Have these crashes occurred with the `FixConveyor` (Conveyor network performance fixes) configuration option ON or OFF?

Hey sorry missed your question, its set to enabled


  <FixConveyor>true</FixConveyor>

FWIW we haven't had an error from it since 7/1, and also haven't seen crashes in instances where we did have it disabled.

**Comment by viktor-ferenczi** [comment]
Great, so disabling that resolved your issue. `FixConveyor` is disabled by default on servers, so we should be good then.
